SITW_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^utd/', include('UTD.urls', namespace='UTD')),

    # login-logout
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
]

UTD/urls.py
from django.conf.urls import url, patterns

from UTD.views import APISongDetail, APIAlbumDetail, APIArtistDetail, APIArtistList, APIUserDetail, APIUserList, \
    APIPlaylistDetail, APIProviderDetail, ProvidersCreate, ProvidersDelete
from UTD.views import ArtistList, ArtistDetails, AlbumList, AlbumDetails, SongList, SongDetails, ArtistCreate, \
    Providers, FollowedArtists, DisplayPlaylist, ProfileView, follow_artist, unfollow_artist, index, Playlists, \
    PlaylistCreate, PlaylistEdit, PlaylistDelete


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^artists/$', ArtistList.as_view(), name='artist_list'),
    url(r'^artists/(?P<pk>\d+)/$', ArtistDetails.as_view(), name='artist_detail'),
    url(r'^artists/(?P<pk>\d+)/albums/$', AlbumList.as_view(), name='artist_albums'),
    url(r'^artists/(?P<pk>\d+)/follow$', follow_artist, name="artist_follow"),
    url(r'^artists/(?P<pk>\d+)/unfollow$', unfollow_artist, name="artist_unfollow"),
    url(r'^artists/create', ArtistCreate.as_view(), name="artist_create"),

    url(r'^albums/(?P<pk>\d+)/$', AlbumDetails.as_view(), name='album_detail'),
    url(r'^albums/(?P<pk>\d+)/songs/$', SongList.as_view(), name='album_songs'),
    url(r'^albums/(?P<pk>\d+)/providers/$', Providers.as_view(),
        name='album_providers'),
    url(r'^albums/(?P<pk>\d+)/providers/create', ProvidersCreate.as_view(), name='provider_create'),
    url(r'^songs/(?P<pk>\d+)/$', SongDetails.as_view(), name='song_detail'),

    url(r'^providers/(?P<pk>\d+)/delete', ProvidersDelete.as_view(), name='provider_delete'),

    # url(r'^user/(?P<pk>\d+)/providers/$', ),
    url(r'^user/(?P<username>[^/]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^user/(?P<username>[^/]+)/following/$', FollowedArtists.as_view(),
        name='followed_artists'),
    url(r'^user/(?P<username>[^/]+)/playlists/$', Playlists.as_view(), name='playlist_details'),
    url(r'^user/(?P<username>[^/]+)/playlists/(?P<pk>\d+)/$', DisplayPlaylist.as_view(), name='playlist_songs'),
    url(r'^user/(?P<username>[^/]+)/playlists/create/$', PlaylistCreate.as_view(), name= 'create_playlist'),
    url(r'^user/(?P<username>[^/]+)/playlists/(?P<pk>\d+)/modify/$', PlaylistEdit.as_view(), name= 'edit_playlist'),
    url(r'^user/(?P<username>[^/]+)/playlists/(?P<pk>\d+)/delete/$', PlaylistDelete.as_view(), name= 'delete_playlist'),
    #url(r'^user/(?P<username>[^/]+)/playlist/$', DisplayPlaylist.as_view()),
]


# REST API patterns
urlpatterns += patterns(
    'UTD.views',
    url(r'^api/$', 'api_root'),
    url(r'^api/artists/$', APIArtistList.as_view(), name='artist-list'),
    url(r'^api/artists/(?P<pk>\d+)/$', APIArtistDetail.as_view(), name='artist-detail'),

    # url(r'^api/albums/$'),
    url(r'^api/albums/(?P<pk>\d+)/$', APIAlbumDetail.as_view(), name='album-detail'),

    # url(r'^api/songs/$'),
    url(r'^api/songs/(?P<pk>\d+)/$', APISongDetail.as_view(), name='song-detail'),

    url(r'^api/users/$', APIUserList.as_view(), name='user-list'),
    url(r'^api/users/(?P<username>.+)/$', APIUserDetail.as_view(), name='user-detail'),

    url(r'^api/playlists/(?P<pk>\d+)/$', APIPlaylistDetail.as_view(), name='playlist-detail'),

    url(r'^api/providers/(?P<pk>\d+)/$', APIProviderDetail.as_view(), name='provider-detail')
)

UTD/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth.signals import user_logged_in
import django

# Create your models here.


class Artist(models.Model):
    name = models.TextField()
    related = models.ManyToManyField('self', symmetrical=True, related_name='related', blank=True)
    spotify_id = models.TextField(unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class Album(models.Model):
    name = models.TextField(default="Unknown")
    artist = models.ForeignKey(Artist)
    release_date = models.DateField()

    def __unicode__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('UTD:album-detail', kwargs={'pkr': self.artist.pk, 'pk': self.pk})


class Song(models.Model):
    name = models.TextField()
    album = models.ForeignKey(Album)

    def __unicode__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('UTD:song-detail', kwargs={'pkr': self.album.pk, 'pk': self.pk})


class Provider(models.Model):
    provider_name = models.TextField()
    album = models.ForeignKey(Album)
    link = models.URLField()
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u'%s' % self.provider_name


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    followed_artist = models.ManyToManyField(Artist, blank=True)


# Create an UserProfile when an user is created.
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile_for_new_user(sender, created, instance, **kwargs):
    if created:
        profile = UserProfile(user=instance)
        profile.save()


class Playlist(models.Model):
    name = models.TextField()
    user = models.ForeignKey(User)
    songs = models.ManyToManyField(Song, blank=True)
    last_update = models.DateField(default=django.utils.timezone.now)

    class Meta:
        unique_together = ('name', 'user',)

    def __unicode__(self):
        return u'%s' % self.name


# update the playlist.
def update_playlists(sender, user, request, **kwargs):
    print "Updating playlist"
    try:
        playlist = Playlist.objects.get(user=user, name='Following')
        artists = user.userprofile.followed_artist.all()
        for artist in artists:
            albums = Album.objects.filter(artist=artist)

            gen = (album for album in albums if album.release_date > playlist.last_update)
            for album in gen:
                songs = Song.objects.filter(album=album)
                playlist.songs.add(*songs)

        playlist.last_update = django.utils.timezone.now()
        playlist.save()

    except Playlist.DoesNotExist:
        playlist = Playlist(user=user, name='Following')
        playlist.last_update = django.utils.timezone.now()
        playlist.save()

        artists = user.userprofile.followed_artist.all()
        for artist in artists:
            print "Adding albums from artist %s" % artist.name
            albums = Album.objects.filter(artist=artist)
            for album in albums:
                songs = Song.objects.filter(album=album)
                print "Adding songs from algum %s" % album.name
                playlist.songs.add(*songs)


user_logged_in.connect(update_playlists)

UTD/forms.py
from django.forms import ModelForm
from models import Provider, Playlist, Artist
from django import forms


class ProviderForm(ModelForm):
    class Meta:
        model = Provider
        exclude = ['album', 'user']
        widgets = {
            'provider_name': forms.TextInput()
        }


class PlaylistForm(ModelForm):
    class Meta:
        model = Playlist
        exclude = ['user', 'songs', 'last_update']
        widgets = {
            'name': forms.TextInput()
        }


class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(),
            'spotify_id': forms.TextInput(attrs={'readonly':'readonly'}),
        }

UTD/views.py
from UTD.forms import ProviderForm, ArtistForm, PlaylistForm
from models import Artist, Album, Song, Provider, Playlist
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateResponseMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
import spotify_handler


def index(request):
    return render(request, 'index.html')

# REST API IMPORTS
from rest_framework import generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.reverse import reverse
from rest_framework.response import Response
from rest_framework import permissions

from serializers import SongSerializer, AlbumSerializer, ArtistSerializer, UserSerializer, PlaylistSerializer, \
    ProviderSerializer


class FormatResponseMixin(TemplateResponseMixin):

    @staticmethod
    def render_to_json_response(objects, **kwargs):
        return HttpResponse(serializers.serialize('json', objects, **kwargs), content_type='application/json')

    @staticmethod
    def render_to_xml_response(objects, **kwargs):
        return HttpResponse(serializers.serialize('xml', objects, **kwargs), content_type='application/xml')

    def render_to_response(self, context, **kwargs):
        # Look for a 'format=json' GET argument
        representation_format = self.request.GET.get('format', '')
        if format is not "":
            try:
                objects = [self.object]
            except AttributeError:
                objects = self.object_list

            if representation_format == 'json':
                return self.render_to_json_response(objects=objects)
            elif representation_format == 'xml':
                return self.render_to_xml_response(objects=objects)
        return super(FormatResponseMixin, self).render_to_response(context)


class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class CheckIsOwnerMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user:
            raise PermissionDenied
        return obj

# Views-----------------------


class ArtistList(ListView, FormatResponseMixin):
    model = Artist
    template_name = 'artistslist.html'
    context_object_name = 'artists_list'  # the name of the object_list used in the template.

    def get_context_data(self, **kwargs):
        context = super(ArtistList, self).get_context_data(**kwargs)
        context['titlehead'] = 'Artists list'
        context['pagetitle'] = 'Artists list'
        return context


class ArtistDetails(DetailView, FormatResponseMixin):
    model = Artist
    template_name = 'artist.html'

    def get_context_data(self, **kwargs):
        context = super(ArtistDetails, self).get_context_data(**kwargs)
        context['titlehead'] = 'Artist'
        context['pagetitle'] = self.object.name

        try:
            last_album = Album.objects.filter(artist=self.object).order_by('-release_date')[0]
        except IndexError:
            last_album = None
        context['album'] = last_album
        return context


class ArtistCreate(CreateView):
    template_name = "artist_form.html"
    form_class = ArtistForm
    success_url = "/utd/artists"

    def form_valid(self, form):
        return_value = super(ArtistCreate, self).form_valid(form)
        spotify_handler.load_albums(form.instance)
        return return_value


class AlbumList(ListView, FormatResponseMixin):
    template_name = 'albumslist.html'
    context_object_name = 'albums_list'  # the name of the object_list used in the template.

    def get_queryset(self):
        self.artist = get_object_or_404(Artist, pk=self.kwargs['pk'])
        return Album.objects.filter(artist=self.artist)

    def get_context_data(self, **kwargs):
        context = super(AlbumList, self).get_context_data(**kwargs)
        context['titlehead'] = 'Albums list'
        context['pagetitle'] = 'Albums list'
        context['artist'] = self.artist
        return context


class AlbumDetails(DetailView, FormatResponseMixin):
    model = Album
    template_name = 'album.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumDetails, self).get_context_data(**kwargs)
        context['titlehead'] = 'Album %s' % self.object.name
        context['pagetitle'] = 'Album %s' % self.object.name
        return context


class SongList(ListView, FormatResponseMixin):
    template_name = 'songslist.html'
    context_object_name = 'songs_list'

    def get_queryset(self):
        self.album = get_object_or_404(Album, pk=self.kwargs['pk'])
        return Song.objects.filter(album=self.album)

    def get_context_data(self, **kwargs):
        context = super(SongList, self).get_context_data(**kwargs)
        context['titlehead'] = 'Songs list'
        context['pagetitle'] = 'Songs list'
        context['album'] = self.album
        return context


class SongDetails(DetailView, FormatResponseMixin):
    model = Song
    template_name = 'song.html'

    def get_context_data(self, **kwargs):
        context = super(SongDetails, self).get_context_data(**kwargs)
        context['titlehead'] = 'Song %s' % self.object.name
        context['pagetitle'] = 'Song %s' % self.object.name
        return context


class RelatedArtistList(ListView, FormatResponseMixin):
    template_name = 'related_artist_list.html'
    context_object_name = 'artist_list'

    def get_queryset(self):
        self.principal_artist = get_object_or_404(Artist, pk=self.kwargs['pk'])
        return self.principal_artist.related.all()

    def get_context_data(self, **kwargs):
        context = super(RelatedArtistList, self).get_context_data(**kwargs)
        context['titlehead'] = 'Related artists'
        context['pagetitle'] = 'Related artists'
        return context


class Providers(ListView, FormatResponseMixin):
    template_name = 'album_provider.html'
    context_object_name = 'provider_list'

    def get_queryset(self):
        self.album = get_object_or_404(Album, pk=self.kwargs['pk'])
        return Provider.objects.filter(album=self.album)

    def get_context_data(self, **kwargs):
        context = super(Providers, self).get_context_data(**kwargs)
        context['titlehead'] = self.album.name
        context['pagetitle'] = self.album.name
        context['album'] = self.album
        return context


class Playlists(ListView, FormatResponseMixin):
    template_name = 'playlist_list.html'
    context_object_name = 'playlist_list'

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['username'])
        return Playlist.objects.filter(user=self.user)

    def get_context_data(self, **kwargs):
        context = super(Playlists, self).get_context_data(**kwargs)
        context['titlehead'] = 'Playlists'
        context['pagetitle'] = 'Playlists'
        return context


class ProvidersCreate(LoginRequiredMixin, CreateView):
    model = Provider
    template_name = 'provider_form.html'
    form_class = ProviderForm

    def form_valid(self, form):
        form.instance.album = Album.objects.get(id=self.kwargs['pk'])
        form.instance.user = self.request.user
        return super(ProvidersCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy('UTD:album_providers', kwargs={'pk': self.kwargs['pk']})


class PlaylistCreate(LoginRequiredMixin, CreateView):
    model = Playlist
    template_name = 'form.html'
    form_class = PlaylistForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PlaylistCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy('UTD:playlist_details', kwargs={'username': self.request.user})


class ProvidersDelete(CheckIsOwnerMixin, DeleteView):
    model = Provider

    def get_success_url(self, **kwargs):
        return reverse_lazy('UTD:album_providers', kwargs={'pk': self.album_pk})

    def delete(self, request, *args, **kwargs):
        return super(ProvidersDelete, self).delete(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.album_pk = self.get_object().album.pk
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(ProvidersDelete, self).post(request, *args, **kwargs)


class FollowedArtists(ListView, FormatResponseMixin):
    template_name = 'followed_artists.html'
    context_object_name = 'followed_artists'

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['username'])
        return self.user.userprofile.followed_artist.all()

    def get_context_data(self, **kwargs):
        context = super(FollowedArtists, self).get_context_data(**kwargs)
        context['titlehead'] = 'Followed artists'
        context['pagetitle'] = 'Followed artists by: %s' % self.user
        return context


class DisplayPlaylist(ListView, FormatResponseMixin):
    template_name = 'display_playlist.html'
    context_object_name = 'song_list'

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['username'])
        self.playlist_name = get_object_or_404(Playlist, pk=self.kwargs['pk'])

UTD/templates/album.html
{% extends 'basepage.html' %}
{% block content %}
 <p vocab="http://schema.org/" typeof="MusicAlbum">
        Album name:  <span property = "Name">{{ album.name }}</span>
        [<span typeof="MusicGroup" rel="byArtist">
        	<span property="name"><a href="{% url 'UTD:artist_detail' pk=album.artist.pk format='' %}">{{ album.artist.name }}</a>
            </span>
        </span>]
        <br>
        Release date: <span property="DatePublished">{{ album.release_date }}</span>
        <br>
        <br>
        <a href="{% url 'UTD:album_providers' pk=album.pk format='' %}">Album providers</a>
</p>
    <p>
        <a href="{% url 'UTD:album_songs' pk=album.pk format='' %}">Songs</a>
    </p>
{% endblock %}

UTD/templates/album_provider.html
{%  extends "basepage.html" %}
{%  block content %}
    <ul>
        {% for provider in provider_list %}
            <li>
                <a href="{{ provider.link }}" target="_blank">{{ provider.provider_name }} &lt;{{ provider.link }}&gt;</a>
                {% if provider.user ==  user %}
                    &nbsp;<a href="{% url "UTD:provider_delete" pk=provider.pk %}">(Delete)</a>
                {% else %}
                    &nbsp;(Added by: {{ provider.user.username }})
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <br>
    <br>
    <a href="{% url "UTD:provider_create" pk=album.pk %}">Add a provider</a>
    <br>
    <a href="{% url "UTD:album_detail" pk=album.pk format='' %}">Back to album.</a>
{%  endblock %}

UTD/templates/albumslist.html
{%  extends "basepage.html" %}
{%  block content %}
<ul>
    {% for album in albums_list %}
        <li><a href="{% url 'UTD:album_detail' pk=album.pk format='' %}">{{ album.name }}</a></li>
    {% endfor %}
</ul>

    Back to artist <a href="{% url 'UTD:artist_detail' pk=artist.pk format='' %}">{{ artist.name }}</a>
{%  endblock %}

UTD/templates/artist.html
{% extends 'basepage.html' %}
{% block content %}
    <div vocab="https://schema.org" typeof="MusicGroup">
        <p>
            Artist: <span property="name">{{ artist.name }}</span>
            <br>
            {% if not user.is_anonymous %}
                <a href="{% url 'UTD:artist_follow' artist.pk %}">Follow</a></li>
            {% endif %}
            <br>
            {% if album != None %}
                <span typeof="MusicAlbum" rel="album">
                    Last album released: <span property="name"><a href="{% url 'UTD:album_detail' pk=album.pk format='' %}">{{ album }}</a></span>
                </span>
            <br>
            {% endif %}
            <a href="{% url 'UTD:artist_albums' pk=artist.pk format=''%}">More albums</a>
        </p>
    </div>
{% endblock %}

UTD/templates/artist_form.html
{% extends "basepage.html" %}
{% block content %}
    {% load staticfiles %}
    <script src="{% static 'artist_form.js'%}"></script>
    <form action="" method="post" id="form">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" />
    </form>
{% endblock %}

UTD/templates/artistslist.html
{%  extends "basepage.html" %}
{%  block content %}
<ul>
    {% for artist in artists_list %}
        <li>
            <a href="{% url 'UTD:artist_detail' pk=artist.pk format='' %}">{{ artist.name }}</a>
            {% if not user.is_anonymous %}
                {% if artist in user.userprofile.followed_artist.all %}
                    <a href="{% url 'UTD:artist_unfollow' artist.pk %}">Unfollow</a></li>
                {% else %}
                    <a href="{% url 'UTD:artist_follow' artist.pk %}">Follow</a></li>
                {% endif %}
            {% endif %}
    {% endfor %}
</ul>
    <br>
    <a href="{% url "UTD:artist_create" %}">Create new artist.</a>
{%  endblock %}

UTD/templates/basepage.html
<html>
  <head>
  <title>{{ titlehead}}</title>

      <!-- ajax scripts -->
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-2.2.3.js"></script>
  <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

  </head>
<body>
    <div>
        {% if user.is_anonymous %}
            Not logged in.
            <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
        {% else %}
            User: {{ user }}
            <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
        {% endif %}
        <hr>
    </div>

    <h1>{{ pagetitle }}</h1>

{% block content %}
{% endblock %}

    <hr>
    <a href="{% url 'UTD:index' %}">Back to main</a>

</body>
</html>

UTD/templates/display_playlist.html
{%  extends "basepage.html" %}
{%  block content %}
<ul>
    {% for song in song_list %}
        <li>{{ song.name }}</li>
    {% endfor %}
</ul>
{%  endblock %}

UTD/templates/followed_artists.html
{%  extends "basepage.html" %}
{%  block content %}
<ul>
    {% for artist in followed_artists %}
        <li>{{ artist.name }} <a href="{% url 'UTD:artist_unfollow' artist.pk %}">Unfollow</a></li>
    {% endfor %}
</ul>
{%  endblock %}

UTD/templates/form.html
{% extends 'basepage.html' %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit" />
    </form>
{% endblock %}

UTD/templates/index.html
{%  extends "basepage.html" %}
{% block content %}
    Hello there.
    Start using our app with the list of <a href="{% url 'UTD:artist_list' %}">artists</a> or <a href="{% url 'django.contrib.auth.views.login' %}">login</a>.
{% endblock %}

UTD/templates/profile.html
{% extends "basepage.html" %}
{% block content %}
    Name: {{ user_profile.first_name }} {{ user_profile.last_name }} <br>
    e-mail: {{ user_profile.email }} <br>
    Followed artists:
    <ul>
        {% for artist in user_profile.userprofile.followed_artist.all %}
            <li><a href="{% url 'UTD:artist_detail' pk=artist.pk %}"> {{ artist.name }}</a></li>
        {% endfor %}

    </ul>

{% endblock %}

UTD/templates/related_artist_list.html
{%  extends "basepage.html" %}
{%  block content %}
<ul>
    {% for artist in artist_list %}
        <li>{{ artist.name }}</li>
    {% endfor %}
</ul>
{%  endblock %}

UTD/templates/songslist.html
{% extends 'basepage.html' %}
{% block content %}
    <div vocab="https://schema.org/" typeof="MusicAlbum">
    <ul rel="track">
        {% for song in songs_list %}
            <li typeof="MusicRecording"><span property="name"><a href="{% url 'UTD:song_detail' pk=song.pk format='' %}">{{ song.name }}</a></span></li>
        {% endfor %}
    </ul>
    Back to album <span property="name"><a href="{% url 'UTD:album_detail' pk=album.pk format='' %}">{{ album.name }}</a></span>
    </div>
{% endblock %}